name: ci

on:
  pull_request:
    branches:
     - main
     - dev
  
  push:
    branches:
     - main
     - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Run docker build
      run: docker build .

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -covermode=count ./...
